### ISSUE TITLE
out of memory allocating 1073745919 bytes

### ISSUE THREAD

**Issue by edenreich** [MeLikeyCode/QtGameEngine#26]
**Summary**
Attempt to build example1 for the first time throws out of memory exception.

**OS / Softwares / Compilers**
-  Windows 10
-  QT v5.9.0
- MinGW 5.3.0 32 bit

**Steps to Reproduce**
Clone the repository and try to build example1

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/16985712/49703748-596cae00-fc09-11e8-9308-e40e5f00b22e.png)

**Suggestion**
Add directive resources_big to CONFIG

**Comment by MeLikeyCode** [comment]
Nice catch! Thank you!
